version: '3'

services:
  db:
    image: postgres:12.10
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
    # command: python3 manage.py runserver 0.0.0.0:8000 --settings=config.settings.development
    volumes:
      - .:/code
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: ./dockerfiles/client/Dockerfile
    ports:
      - "3000:3000"
    working_dir: "/code"
    command: npm run dev
    volumes:
      - "./frontend:/code"
      - node_modules_volume:/frontend/node_modules
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume: