# Generated by Django 3.2 on 2022-02-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mistaken_words',
            new_name='mistake_words',
        ),
    ]
