# Generated by Django 3.2 on 2021-11-11 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordname', models.CharField(max_length=128, verbose_name='単語')),
                ('meaning', models.CharField(max_length=128, verbose_name='意味')),
                ('pos', models.CharField(max_length=128, verbose_name='品詞')),
                ('language', models.CharField(max_length=128, verbose_name='言語')),
                ('freq', models.IntegerField(blank=True, verbose_name='出現回数')),
                ('mistake_users', models.ManyToManyField(related_name='mistake_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vocabulary',
            },
        ),
    ]
