# Generated by Django 3.2 on 2022-02-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordname', models.CharField(max_length=128, verbose_name='単語')),
                ('meaning', models.CharField(max_length=128, verbose_name='意味')),
                ('pos', models.CharField(max_length=128, verbose_name='品詞')),
                ('language', models.CharField(max_length=128, verbose_name='言語')),
                ('freq', models.IntegerField(blank=True, verbose_name='出現回数')),
            ],
            options={
                'db_table': 'words',
            },
        ),
    ]
