# Generated by Django 3.2 on 2022-02-09 12:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vocabulary',
            new_name='Word',
        ),
        migrations.AlterModelTable(
            name='word',
            table='words',
        ),
    ]
