name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-web-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: APIサーバをデプロイ
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SECRET_KEY }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd wordbook-app/
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart wordbook
            
  deploy-spa-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SPAクライアントのデプロイ
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SECRET_KEY }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd wordbook-app/
            git pull origin main
            cd frontend
            npm install --legacy-peer-deps
            npm run generate
            sudo rm -rf /var/www/wordbook-app/frontend
            sudo cp -r ./dist /var/www/wordbook-app/frontend
            sudo nginx -s reload
      
